# docker-compose.yml
version: '3.8'

services:
  redis-1:
    image: redis:7-alpine
    container_name: redis-1
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7001:6379"
    networks:
      - redis-net

  redis-2:
    image: redis:7-alpine
    container_name: redis-2
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7002:6379"
    networks:
      - redis-net

  redis-3:
    image: redis:7-alpine
    container_name: redis-3
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7003:6379"
    networks:
      - redis-net

  redis-4:
    image: redis:7-alpine
    container_name: redis-4
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7004:6379"
    networks:
      - redis-net

  redis-5:
    image: redis:7-alpine
    container_name: redis-5
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7005:6379"
    networks:
      - redis-net

  redis-6:
    image: redis:7-alpine
    container_name: redis-6
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7006:6379"
    networks:
      - redis-net

  python-app:
    build: ./python-app
    container_name: python-app
    networks:
      - redis-net
    depends_on:
      - redis-1
      - redis-2
      - redis-3

  php-app:
    build: ./php-app
    container_name: php-app
    networks:
      - redis-net
    depends_on:
      - redis-1
      - redis-2
      - redis-3

networks:
  redis-net:
    driver: bridge
